name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      # Step to install Android SDK
      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;33.0.0" "platforms;android-33"

      # Set ADB in PATH
      - name: Set up ADB in PATH
        run: echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      # Set ANDROID_HOME environment variable
      - name: Set ANDROID_HOME environment variable
        run: echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV

      # Step to start Appium server
      - name: Start Appium Server
        run: |
          npm install -g appium
          appium --address 127.0.0.1 --port 4723 &

      # Install ngrok and expose ADB over TCP
      - name: Install ngrok
        run: |
          curl -s https://ngrok.com/download | unzip -d /tmp/ngrok
          sudo mv /tmp/ngrok /usr/local/bin/

      - name: Expose ADB via ngrok
        run: |
          ngrok tcp 5037 &  # This exposes ADB on port 5037
          sleep 10           # Wait for ngrok to establish the tunnel

      # Connect to Real Device via ngrok ADB
      - name: Connect to Real Device via ngrok ADB
        run: |
          adb connect $(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' | sed 's/tcp:\/\//')
          adb devices

      # Run tests
      - name: Run tests
        run: npx wdio run ./wdio.conf.js

      # Generate Allure Report
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean
          allure open
