name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: self-hosted  # Apne machine ka use karega

    steps:
      # Step 1: Checkout the repository for  GitHub Actions ko aapke repository ka access
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies (If needed, you can skip if dependencies are already in your system)
      - name: Install dependencies
        run: npm install

      # Step 3: Start Appium server (ensure it's installed on the self-hosted runner)
      - name: Start Appium Server
        run: |
          npm install -g appium
          appium --address 127.0.0.1 --port 4723 &

      # Step 4: Run tests using WebDriverIO
      - name: Run tests
        run: npx wdio run ./wdio.conf.js

      # Step 5: Generate Allure report and open it
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean
          allure open
