name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Step to install Android SDK
      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk
          sudo apt install -y wget unzip
          # Install Android SDK command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk
          # Install SDK packages (platform-tools, build-tools, etc.)
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;33.0.0" "platforms;android-33"

      # Add platform-tools to PATH so adb is available
      - name: Set up ADB in PATH
        run: echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      # Set environment variables
      - name: Set ANDROID_HOME environment variable
        run: echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV

      # Step to start Appium server
      - name: Start Appium Server
        run: |
          npm install -g appium
          appium --address 127.0.0.1 --port 4723 &

      # Step to connect to Android device over Wi-Fi
      - name: Connect to Android device over Wi-Fi
        run: |
          adb start-server  # Start adb server if not running
          adb connect 192.168.1.12:5555  # Replace with the IP address of your device

      - name: Run tests
        run: npx wdio run ./wdio.conf.js

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean
          allure open
